WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

program = _{ SOI ~ statement ~ EOI }

statement = { assignment }

assignment = { "let" ~ identifier ~ "=" ~ expression ~ ";" }

expression = { operator ~ expression ~ expression | (number | boolean) }

operator = { "+" | "-" | "*" | "/" |
    "==" | "!=" | "<" | "<=" | ">" | ">="
}

number = @{ ASCII_DIGIT+ }

boolean = @{ "true" | "false" }

identifier = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
