WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

Program = { SOI ~ Statement+ ~ EOI }

Statement = { Assignment ~ ";" }

Assignment = { "let" ~ Identifier ~ "=" ~ Expression }

Expression = { 
    IntegerLiteral | 
    BooleanLiteral |
    UnaryExpression
}

UnaryExpression = { "(" ~ UnaryOperator ~ Expression ~ ")" }

UnaryOperator = { "-" | "not" }

IntegerLiteral = @{ ASCII_DIGIT+ }

BooleanLiteral = @{ "true" | "false" }

Identifier = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
